SEED: 1337 # random seed for reproduce results
DATA_ROOT: '/sd/datasets/' # the parent root where your train/val/test data are stored
INDEX_ROOT: '/sd/datasets/ms1m+mask_tf/'
DATASETS:  # the dataset index name
    - name: ms1m+mask_1.0
      batch_size: 256
      weight: 1.
    
BACKBONE_RESUME: ""
HEAD_RESUME: ""
META_RESUME: ""

# BACKBONE_NAME: 'EfficientNetB0'
BACKBONE_NAME: 'IR_50'
DIST_FC: true
TFRRECORD: true
MODEL_ROOT: '' # the root to buffer your checkpoints
LOG_ROOT: './tensorboard' # the root to log your train/val status
HEAD_NAME: "CurricularFace" # support:  ['ArcFace', 'CurricularFace', 'CosFace']
LOSS_NAME: 'DistCrossEntropy' # support: ['DistCrossEntropy', 'Softmax']
INPUT_SIZE: [112, 112] # support: [112, 112] and [224, 224]
RGB_MEAN: [0.5, 0.5, 0.5] # for normalize inputs to [-1, 1]
RGB_STD: [0.5, 0.5, 0.5]
INPUT_SIZE: [112, 112]
EMBEDDING_SIZE: 512 # feature dimension
LR: 0.1 # initial LR
START_EPOCH: 0 # start epoch
WARMUP_STEP: -1
NUM_EPOCH: 36 # total epoch number
WEIGHT_DECAY: 0.0005 # do not apply to batch_norm parameters
MOMENTUM: 0.9
STAGES: [10, 18, 24] # epoch stages to decay learning rate
WORLD_SIZE: 1
RANK: 0
LOCAL_RANK: 0
DIST_BACKEND: 'nccl'
DIST_URL: 'env://'
NUM_WORKERS: 8
AMP: true # fp16 for backbone
